import { DatabaseTypeCode, TableDataType } from '@/constants';
import { SqlTypeEnum } from './sqlParser';

// Identify the database context used for SQL execution and metadata queries.
export interface IDBContextInfo {
  dataSourceId?: number;
  databaseName?: string;
  schemaName?: string;
  databaseType?: DatabaseTypeCode;
  dataSourceName?: string;
}

export interface IDatabaseBaseInfo {
  dataSourceId?: number;
  dataSourceName?: string;
  databaseType?: DatabaseTypeCode;
  databaseName?: string;
  schemaName?: string;
  tableName?: string;
  sql?: string;
  connectable?: boolean;
}

export interface IDatabaseItem {
  name: string;
  description: string;
  count: number;
}

export interface IDatabase {
  name: string;
  code: DatabaseTypeCode;
  icon: string;
  iconExistDark?: boolean;
  supportDatabase: boolean;
  supportSchema: boolean;
  needAiDataCollections?: boolean;
}

export interface ITableHeaderItem {
  dataType: TableDataType;
  name: string;
  columnName?: string;
  columnType?: string;
  editorType?: ResultSetEditorType;
  tableName?: string;
  autoIncrement?: boolean | number | null; // Whether to increment automatically
  columnSize?: number | null; // field length
  comment?: string | null; // Field annotation
  decimalDigits?: number | null; // Decimal places
  defaultValue?: string | null; // Default value
  nullable?: boolean | null; // Is it empty
  primaryKey?: boolean | null; // Is it a primary key?
}

export type ResultSetEditorType = 'TEXT' | 'DATE' | 'TIME' | 'DATETIME' | 'TIMESTAMP';

export type LargeValueType = 'TEXT' | 'BINARY' | 'IMAGE' | 'JSON' | 'UNKNOWN';

export interface IResultCell {
  value: string | null;
  largeValue?: boolean;
  largeValueId?: string;
  valueType?: LargeValueType;
  sqlType?: number;
  columnType?: string;
  sizeBytes?: number;
  sizeChars?: number;
  loadedBytes?: number;
  loadedChars?: number;
  truncated?: boolean;
  unsupportedReason?: string;
}

export interface ILargeCellChunk {
  value: string;
  offset: number;
  nextOffset: number;
  eof: boolean;
  sizeBytes?: number;
  sizeChars?: number;
  encoding?: string;
  contentType?: string;
  displayMode?: LargeValueType;
}

export interface ILargeCellValueRequest {
  largeValueId: string;
  offset?: number;
  limit?: number;
  format?: 'text' | 'hex' | 'base64' | 'auto';
}

export interface ILargeCellDownloadRequest {
  largeValueId: string;
  format?: 'raw' | 'text' | 'hex';
}

// The sql that needs to be executed exposed by the console
export interface IConsoleReturnExecuteSql {
  sql: string;
  single?: boolean;
  // Approval ID
  applyId?: number;
}

// View all parameters from the table
export interface IViewTableParams {
  dataSourceId?: number;
  databaseName?: string;
  databaseType?: DatabaseTypeCode;
  schemaName?: string;
  tableName?: string;
  pageNo?: number;
  pageSize?: number;
}

// Execute all parameters that SQL depends on
export interface IExecuteSqlParams extends IConsoleReturnExecuteSql {
  dataSourceId?: number;
  dataSourceName?: string;
  databaseName?: string;
  databaseType?: DatabaseTypeCode;
  schemaName?: string;
  tableName?: string;
  resultSetId?: number; // The result set id generated by the backend
  pageNo?: number;
  pageSize?: number;
}

export interface ISqlExecutionMessage {
  level?: 'INFO' | 'WARN' | 'ERROR';
  message: string;
  errorCode?: number;
  sqlState?: string | null;
  source?: string;
  resultSetId?: number;
}

export interface IExecutionMetrics {
  startedAtEpochMs?: number;
  finishedAtEpochMs?: number;
  totalDurationMs?: number;
  executeDurationMs?: number;
  fetchDurationMs?: number;
  fetchedRowCount?: number;
}

export interface IExecutionContext {
  databaseName?: string;
  schemaName?: string;
}

export interface IManageResultData {
  // The uuid generated by the front end itself
  uuid?: string;
  displayName?: string;

  dataList: IResultCell[][];
  headerList: ITableHeaderItem[];
  description: string;
  message?: string;
  sql: string;
  originalSql: string;
  success: boolean;
  duration: number;
  updateCount?: number; // If it is modified. The backend will return the number of modified items
  canEdit?: boolean; // Whether the returned data can be edited
  // Editable results include the table name required for update requests.
  tableName?: string;
  sqlType: SqlTypeEnum;
  refreshTargets: IRefreshTargets[];
  comment?: string; // Comment
  resultSetId?: number; // The result set id generated by the backend
  statementSequence?: number;
  executionMetrics?: IExecutionMetrics;
  executionContext?: IExecutionContext;
  extra?: {
    messages?: ISqlExecutionMessage[];
    [key: string]: any;
  };

  // Pagination information
  pageNo: number;
  pageSize: number;
  fuzzyTotal: string;
  hasNextPage: boolean;

  // Subsequent paging/where/order by and other operations need to carry sql execution parameters
  executeSqlParams?: IExecuteSqlParams;
}

export interface IRefreshTargets {
  dataSourceId: number;
  databaseName: string;
  schemaName: string;
  tableName: string;
}

/** Query results configuration properties */
export interface IResultConfig {
  pageNo: number;
  pageSize: number;
  total: number | string;
  hasNextPage: boolean;
}

/** List of column field types and character sets supported by different databases and arrangement rules */
export interface IDatabaseSupportField {
  columnTypes: IColumnTypes[];
  charsets: ICharset[];
  collations: ICollation[];
  indexTypes: IIndexTypes[];
  defaultValues: IDefaultValue[];
  engineTypes: IEngineType[];
}

/** The character set corresponding to the field */
export interface ICharset {
  charsetName: string; // Character set name
  defaultCollationName: string; // Character set default collation
}

/** Arrangement rules */
export interface ICollation {
  collationName: string;
}

/** Type of index */
export interface IIndexTypes {
  typeName: string;
}

/** Table engine type */
export interface IEngineType {
  name: string;
}

/** Column field types supported by different databases and supported adjustment options */
export interface IColumnTypes {
  typeName: string;
  supportAutoIncrement: boolean; // Whether to support self-increment
  supportCharset: boolean; // Whether character set is supported
  supportCollation: boolean; // Whether to support sorting rules
  supportComments: boolean; // Whether to support comments
  supportDefaultValue: boolean; // Whether to support default value
  supportExtent: boolean; // Whether to support extensions
  supportLength: boolean; // Whether to support length
  supportNullable: boolean; // Whether to support empty
  supportScale: boolean; // Whether to support decimal places
  supportValue: boolean; // Whether the value is supported
  supportUnit: boolean; // Whether to support the unit
  supportOnUpdateCurrentTimestamp: boolean; // Whether to support ON UPDATE CURRENT_TIMESTAMP
}

/** Different databases support different default values */
export interface IDefaultValue {
  defaultValue: string; // Default value
}

// User configured tree structure information
export interface IUserConfigTree {
  // Whether to display notes
  showComment: boolean;
  // Whether to follow the currently open workspace tab
  followActiveWorkspaceTab?: boolean;
  // The selected workspace sidebar surface
  workspaceLeftPanel?: 'explorer' | 'database';
  // Whether to sort database object nodes by name without changing datasource order
  sortDatabaseObjects?: boolean;
}
